-- Update ATV tour description_en with SEO-optimized long-form content
-- Target keyword: "ATV tour Jacó Costa Rica"

UPDATE tours
SET description_en = 'The rumble of the engine beneath you, the earthy scent of rainforest air, and the first splash of mud as your tires bite into the trail — this is the ATV tour Jacó Costa Rica experience that awaits. Within minutes of leaving town, the pavement disappears and you are threading through dense jungle corridors where howler monkeys call from the canopy above. Sunlight filters through layers of leaves as you climb toward viewpoints that reveal the Pacific Ocean stretching to the horizon. There is nothing quite like cresting a ridge on a jungle ATV adventure with the entire coastline laid out before you.' || E'\n\n' ||
'The route takes you deep into the hills behind Jacó and toward Herradura, following trails that wind through secondary forest, past hidden waterfalls, and across shallow riverbeds that send cool water spraying in every direction. These are real off-road Costa Rica trails — rocky ascents, muddy descents, and sweeping curves that keep your hands and attention engaged. Open pastureland where you can open the throttle, tight single-track through bamboo groves, and gravel roads cutting through palm plantations. The ATV Herradura loop is a highlight, with dramatic views of the Gulf of Nicoya and a chance to spot toucans and iguanas.' || E'\n\n' ||
'If you have never ridden before, this beginner ATV tour includes a full safety orientation and practice session before you hit the trails. Our guides match the pace to the group so first-time riders feel confident while experienced riders get their adrenaline fix. Drivers must be 18 or older, but passengers as young as 5 can ride along on a double-seat ATV. Groups, couples, and solo travelers are all welcome.' || E'\n\n' ||
'Multiple duration options range from one hour to a full-day excursion. The one-hour ride gives you a solid taste of the trails while the half-day option reaches the best viewpoints and river crossings. The full-day experience extends toward the mountains beyond Herradura with a stop for lunch at a local soda. Round-trip transportation from your Jacó or Herradura hotel is included at no extra cost. Wear closed-toe shoes, long pants, and clothes you do not mind getting muddy. Sunscreen, insect repellent, and a change of clothes are recommended. All helmets and safety gear are provided. Every ATV tour Jacó offers includes top-quality machines and professional bilingual guides who know every inch of the terrain.' || E'\n\n' ||
'Ready to hit the trail? Book your ATV adventure in Jacó today and discover why this ATV tour Jacó Costa Rica remains one of the most popular ways to explore the wild side of the country.'
WHERE slug = 'jaco-atv-adventure';
